apiVersion: v1
kind: Namespace
metadata:
  name: chatapp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: chatapp-svc
  namespace: chatapp
spec:
  externalTrafficPolicy: Local
  ports:
    - name: magiconion
      port: 12345
      protocol: TCP
      targetPort: magiconion
  selector:
    app: magiconion
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magiconion
  name: chatapp
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magiconion
  template:
    metadata:
      labels:
        app: magiconion
    spec:
      containers:
        - env:
            - name: DOTNET_ENVIRONMENT
              value: Development
          image: cysharp/magiconion_sample_chatapp:3.0.13-chatapp
          imagePullPolicy: Always
          name: chatapp
          ports:
            - containerPort: 12345
              name: magiconion
